#!/bin/bash
########################################################################
#
#
#                       script: notworked
#                           by: Dan Purgert    
#                    copyright: 2017
#                      version: 0.1
#                         date: Sat Dec 20 10:03:44 EDT 2017
#                      purpose: Print out the system's network info
#                             : to allow the people helping you with a 
#                             : problem to see relevant details.
#
#                      license: GPL v2 (only)
#                   repository: http://github.com/dpurgert
#
#
########################################################################

if [[ "$#" -eq 0 ]] || [[ $1 = '-h' ]] ;then
  printf "  notworked
  ----------

  This script will run several commands that print out the network
  details, and then send the results to a pastebin.  

  To indicate you accept, run the program with the -a switch.

  
  OPTIONS:
     -a -> run the program and send results to pastebin
     -l -> run local-only
     -h -> print this help and exit\n"

  exit 0
fi
     
t1=$(mktemp /tmp/notwork.XXXXX)
t2=$(mktemp /tmp/notwork.XXXXX)

if [[ $EUID -ne 0 ]] ;then
  printf "not running as root, arp table will not be printed.\n"
else
  printf "ARP Table:\n"
  arp |tee $t2 2>&1
  printf "\n\n"
fi


if [[ $1 = "-l" ]]; then
  printf "Routing table:\n"
  ip route

  printf "\n\nInterface addresses:\n"
  ip addr
elif [[ $1 = "-a" ]]; then
  ( printf "Routing table:\n"
    ip route
    printf "\n\nInterface addresses:\n"
    ip addr
    printf "\n\n") >$t1 2>&1
  
  cat $t1 $t2 | nc termbin.com 9999
fi

rm $t1 $t2
